version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
        docker:
          - image: cypress/base:latest
        # environment:
        #   MONGODB_URI: mongodb+srv://lhetland:rootROOT@cluster0.aysiw.mongodb.net/wordGuessTest?retryWrites=true&w=majority&appName=Cluster0
        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm install
          - run:
              name: Build the app
              command: npm run build

workflows:
  run-tests:
    jobs:
      - start-server
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
          