version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

workflows:
  run-tests:
    jobs:
      - cypress/run:
          name: run-component-tests
          cypress-command: npx cypress run --component
          